CREATE TABLE dbo.CharacterPosition (
    CharacterID BIGINT PRIMARY KEY,
    MapID INT NOT NULL DEFAULT 1,
    PosX FLOAT NOT NULL DEFAULT 0,
    PosY FLOAT NOT NULL DEFAULT 0,
    PosZ FLOAT NOT NULL DEFAULT 0,
    Yaw FLOAT NOT NULL DEFAULT 0,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);