CREATE TABLE dbo.Character (
	CharacterID BIGINT IDENTITY(1,1) PRIMARY KEY,
	AccountID BIGINT FOREIGN KEY REFERENCES dbo.Account(AccountID),
	Slot SMALLINT NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Level INT NOT NULL DEFAULT 1,
	Experience BIGINT NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	DeletedAt DATETIME 
);

CREATE TABLE dbo.CharacterInventory (
	InventoryID BIGINT PRIMARY KEY,
	CharacterID BIGINT FOREIGN KEY REFERENCES dbo.Character(CharacterID),
	ItemID BIGINT NOT NULL,
	Quantity INT NOT NULL DEFAULT 1,
	AcquiredAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE dbo.CharacterSkills (
	SkillID BIGINT PRIMARY KEY,
	CharacterID BIGINT FOREIGN KEY REFERENCES dbo.Character(CharacterID),
	SkillName NVARCHAR(100) NOT NULL,
	SkillLevel INT NOT NULL DEFAULT 1,
	AcquiredAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE dbo.CharacterStats (
	StatID BIGINT PRIMARY KEY,
	CharacterID BIGINT FOREIGN KEY REFERENCES dbo.Character(CharacterID),
	Health INT NOT NULL DEFAULT 100,
	Mana INT NOT NULL DEFAULT 100,
	Strength INT NOT NULL DEFAULT 10,
	Agility INT NOT NULL DEFAULT 10,
	Intelligence INT NOT NULL DEFAULT 10,
	UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
